### ISSUE TITLE
Re-Investigations: Add Tier 2SR and Tier 4R For Sponsorship

### ISSUE THREAD

**Issue by ylewis-gsa** [GSA/Suitability#61]
The suitability dll needs to handle Tier 2SR and Tier 4R for sponsorship.

Include:
#63

**Comment by ylewis-gsa** [comment]
Per customer - Attachments have been changed.

Tier 2RS to include
1. Additional Questions for Public Trust Position Form
2. GSA 3665
3. SF85P

Tier 4R: 
1. GSA 3665
2. SF85P

**Comment by tsaunders-gsa** [comment]
Code has been merged into Dev.

Pull Request: https://github.com/GSA/Suitability/pull/62
