### ISSUE TITLE
E-Mail Update: 2 SAC E-Mails

### ISSUE THREAD

**Issue by dlenz-gsa** [GSA/Suitability#7]
New SAC sponsorship e-mail with updated text (text found [here](https://docs.google.com/document/d/1NgA1IQB6lKGmYcaOxPu7Jaff9W8YOscOUuMz2S8BMk4/edit
)), which has an attached 306 ([OF0306.pdf](https://github.com/GSA/Suitability/files/1170462/OF0306.pdf)), will be sent to the following applicant types: 
     Regions 1-10 (Zones A, B, C, D) NOT in Major Org P - NEW 
     Regions NCR & CO (Zone E) - Everybody gets the NEW 

Old SAC e-mails (those currently being used) will be sent to the remaining applicant types: 
     Regions 1-10 (Zones A, B, C, D) in Major Org P - OLD

**Comment by jgoodell-gsa** [comment]
@dlenz-gsa can we set up a meeting for this tomorrow. Might be able to work on it over the weekend. 


/cc @tsaunders-gsa

**Comment by dlenz-gsa** [comment]
Please name new template "SAC_PBS"

**Comment by tsaunders-gsa** [comment]
https://github.com/GSA/Suitability/blob/6ca7e6ec568e7ae5c0b8cfc0fa0b99d8e097d02c/Suitability/SendNotification.cs#L290-#L297

@jgoodell-gsa
